apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: webapp
          image: downloader:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: pguser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: pgpassword
            - name: DB_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: pgdb
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-url
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080